### ISSUE TITLE
packages deprecated

### ISSUE THREAD

**Issue by muneeb-ahmed-mcs** [jesseshowalter/jesseshowalter-starter-project#2]
after executing command npm install it's showing me this:

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! Unexpected end of JSON input while parsing near '...try.npmjs.org/autopre'

**Comment by jesseshowalter** [comment]
New version just updated
